"""Reproduction suite: match the reference TypeScript implementation exactly.

Every expected value here was produced by the `veriva-eval` TypeScript harness
on the same committed panel, not by this package. `panel-comparison.json` ships
as a fixture and is never regenerated by judgecheck; if it were, this suite
would be circular and would prove nothing.

The two implementations share an author, so this is not third-party
replication. What it establishes is narrower: that a port across a language
boundary is faithful, measured against values committed before the port
existed. Narrower, and still the strongest correctness argument here.

`test_the_fixture_has_no_unchecked_fields` keeps the README's claim that the
suite asserts *every* value honest. If the reference harness grows a field,
that test fails until this suite covers it or the claim is softened.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from judgecheck import fleiss_kappa, krippendorff_alpha, load_panel, mean_pairwise_kappa
from judgecheck.agreement import cohens_kappa
from judgecheck.types import Panel

PANEL_DIR = Path(__file__).parent / "data" / "panel-real"
TOLERANCE = 1e-12


@pytest.fixture(scope="module")
def panel() -> Panel:
    return load_panel(PANEL_DIR)


@pytest.fixture(scope="module")
def ts_fixture() -> dict[str, Any]:
    """The TypeScript harness's committed output."""
    raw: dict[str, Any] = json.loads(
        (PANEL_DIR / "panel-comparison.json").read_text(encoding="utf-8")
    )
    return raw


def test_the_fixture_has_no_unchecked_fields(ts_fixture: dict[str, Any]) -> None:
    """Pins the fixture's shape so no value can appear without being asserted."""
    assert set(ts_fixture) == {"generatedFrom", "raters", "pairwiseKappa", "consensus"}
    assert set(ts_fixture["consensus"]) == {"entries"}

    for key, entry in ts_fixture["pairwiseKappa"].items():
        assert set(entry) == {"kappa", "observedAgreement"}, key
    for entry in ts_fixture["consensus"]["entries"]:
        assert set(entry) == {"findingId", "labels", "consensus", "consensusLabel"}
    for name, entry in ts_fixture["raters"].items():
        assert set(entry) == {"name"}, name


def test_reproduces_the_fixture_metadata(panel: Panel, ts_fixture: dict[str, Any]) -> None:
    """The two fields that are not statistics, so 'every value' means every value."""
    assert ts_fixture["generatedFrom"] == panel.name
    assert tuple(sorted(ts_fixture["raters"])) == panel.rater_names
    for name, entry in ts_fixture["raters"].items():
        assert entry["name"] == name


def test_panel_shape(panel: Panel) -> None:
    assert panel.rater_names == ("claude", "deepseek", "gemini", "glm", "gpt", "grok", "qwen")
    assert len(panel.item_ids) == 23
    assert panel.truth is not None
    assert len(panel.truth) == 23
    for name in panel.rater_names:
        assert len(panel.raters[name]) == 23, f"{name} should label all 23 findings"


def test_reproduces_all_21_pairwise_kappa(panel: Panel, ts_fixture: dict[str, Any]) -> None:
    """All 21 pairwise Cohen's kappa values, to 1e-12."""
    expected = ts_fixture["pairwiseKappa"]
    assert len(expected) == 21

    checked = 0
    for pair_key, exp in expected.items():
        a, b = pair_key.split("_")
        got = cohens_kappa(panel.raters[a], panel.raters[b])
        assert got.kappa == pytest.approx(exp["kappa"], abs=TOLERANCE), (
            f"{pair_key}: kappa {got.kappa!r} != TS {exp['kappa']!r}"
        )
        assert got.agreement == pytest.approx(exp["observedAgreement"], abs=TOLERANCE), (
            f"{pair_key}: agreement {got.agreement!r} != TS {exp['observedAgreement']!r}"
        )
        checked += 1
    assert checked == 21


# Published by `npm run replay:real`, regenerated 2026-08-10.
EXPECTED_FLEISS = 0.135
EXPECTED_KRIPPENDORFF = 0.141


def test_reproduces_panel_agreement(panel: Panel) -> None:
    raters = [panel.raters[n] for n in panel.rater_names]

    fk = fleiss_kappa(raters)
    assert round(fk.value, 3) == EXPECTED_FLEISS, f"Fleiss {fk.value!r}"
    assert fk.n == 23
    assert fk.raters == 7
    assert fk.interpretation == "poor"

    ka = krippendorff_alpha(raters)
    assert round(ka.value, 3) == EXPECTED_KRIPPENDORFF, f"Krippendorff {ka.value!r}"
    assert ka.interpretation == "poor"


# Published by `npm run replay:real`, "Rater redundancy (mean pairwise Cohen's kappa)".
EXPECTED_MEAN_PAIRWISE = {
    "claude": 0.257,
    "deepseek": 0.209,
    "gemini": 0.285,
    "glm": 0.146,
    "gpt": 0.285,
    "grok": 0.134,
    "qwen": 0.076,
}


def test_reproduces_mean_pairwise_kappa(panel: Panel) -> None:
    got = mean_pairwise_kappa(dict(panel.raters))
    assert set(got) == set(EXPECTED_MEAN_PAIRWISE)
    for rater, exp in EXPECTED_MEAN_PAIRWISE.items():
        assert round(got[rater], 3) == exp, f"{rater}: {got[rater]!r} != {exp}"
